aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_torsion_shift_controller
# aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_controller

controller:
  xy:
    p_gain: 2.3
    i_gain: 0.02
    d_gain: 4.0
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 3.6
    i_gain: 1.55
    d_gain: 3.4
    limit_err_p: 1.0
    limit_sum: 16.5 # N for clamping thrust force
    limit_p: 10 # m / s^2
    limit_i: 15 # m / s^2
    limit_d: 10 # m / s^2
    landing_err_z: -0.55

  yaw:
    limit_sum: 6.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 4.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: false

  # LQI gain generator
  lqi:
    debug: false
    gain_generate_rate: 15.0
    init_wait_time: 1
    gyro_moment_compensation: false
    clamp_gain: true

    roll_pitch_p: 1100
    roll_pitch_d: 80
    roll_pitch_i: 10

    yaw_p: 10.0
    yaw_i: 0.5
    yaw_d: 0.50

    q_z: 10.0 # direct feedback gain, old: 10.0
    q_z_d: 20.0  # direct feedback gain, old: 20.0
    q_z_i: 10.0  # direct feedback gain, old: 10.0

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1

  gain_shift_matrix_pub_interval: 0.1

  gain_shift:
    null_space_shift_thresh: 0.9
    null_space_shift_limit_ratio: 0.15
    null_space_shift_mix_limit: 1.0
    null_space_shift_max_eval: 1000
    nlopt_use_global: false 
    nlopt_xtol_rel: 0.001
    nlopt_position_penalty: 1.0
    nlopt_alpha: 1.0
