aerial_robot_control_name: aerial_robot_control/hydrus_tilted_fully_actuated_torsion_shift_controller

controller:
  xy:
    p_gain: 2.5
    i_gain: 0.05
    d_gain: 1.5
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 5.0
    i_gain: 1.0
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0

  yaw:
    p_gain: 8.0
    i_gain: 1.0
    d_gain: 4.0
    limit_err_p: 0.4
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0
    need_d_control: false

  roll_pitch:
    p_gain: 25.0
    i_gain: 1.0
    d_gain: 8.0
    limit_sum: 20.0
    limit_p: 20.0
    limit_i: 20.0
    limit_d: 20.0

  gain_shift_matrix_pub_interval: 0.1

  gain_shift:
    null_space_shift_thresh: 0.9
    null_space_shift_limit_ratio: 1.0
    null_space_shift_mix_limit: 0.15
    null_space_shift_max_eval: 1000
    nlopt_use_global: false
    nlopt_xtol_rel: 0.0001
    nlopt_position_penalty: 0.1
    nlopt_alpha: 0.5
