# aerial_robot_control_name: aerial_robot_control/hydrus_lqi_controller
# aerial_robot_control_name: aerial_robot_control/hydrus_lqi_torsion_suppression_controller
# aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_torsion_suppression_controller
aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_torsion_mode_controller
# aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_controller

controller:
  xy:
    p_gain: 2.3
    i_gain: 0.02
    d_gain: 4.0
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 3.6
    i_gain: 1.55
    d_gain: 3.4
    limit_err_p: 1.0
    limit_sum: 16.5 # N for clamping thrust force
    limit_p: 10 # m / s^2
    limit_i: 15 # m / s^2
    limit_d: 10 # m / s^2
    landing_err_z: -0.55

  yaw:
    limit_sum: 6.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 4.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: false

  # LQI gain generator
  lqi:
    debug: true
    gain_generate_rate: 30.0
    init_wait_time: 5
    gyro_moment_compensation: false
    clamp_gain: true

    # no tilt
    # roll_pitch_p: 400
    # roll_pitch_d: 40
    # tilt
    roll_pitch_p: 1100
    roll_pitch_d: 80
    roll_pitch_i: 10

    # no tilt
    yaw_p: 10.0
    yaw_i: 0.5
    yaw_d: 0.50
    # tilt
    # yaw_p: 100
    # yaw_i: 0.5
    # yaw_d: 50

    q_z: 10.0 # direct feedback gain, old: 10.0
    q_z_d: 20.0  # direct feedback gain, old: 20.0
    q_z_i: 10.0  # direct feedback gain, old: 10.0

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1

    # torsion_control torsional_spring_constant: 50.0
    mode_num: 4
    q_mu: [1, 1, 1, 1]
    q_mu_d: [1, 1, 1, 1]
    use_rbdl_b_rot: false

    torsion_epsilon_rp_p: 0.1
    torsion_epsilon_rp_i: 0.1
    torsion_epsilon_rp_d: 0.1
    torsion_epsilon_y_p: 0.1
    torsion_epsilon_y_i: 0.1
    torsion_epsilon_y_d: 0.1
    torsion_alpha_rp_p: 0.1
    torsion_alpha_rp_i: 0.1
    torsion_alpha_rp_d: 0.2
    torsion_alpha_y_p: 0.2
    torsion_alpha_y_i: 0.2
    torsion_alpha_y_d: 0.2
